//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TavParkBJV
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiftGecis
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Plaka { get; set; }
        public string Lokasyon { get; set; }
        public string Model { get; set; }
        public string Firma { get; set; }
        public string Eylem { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> Ucret { get; set; }
        public string OdemeYontemi { get; set; }
        public string YapilanIslem { get; set; }
        public string Personel { get; set; }
        public string Saat { get; set; }
        public string ext1 { get; set; }
        public string ext2 { get; set; }
    }
}
