//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TavParkBJV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gelirler
    {
        public int Id { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public string Tanim { get; set; }
        public Nullable<decimal> SatisGeliri { get; set; }
        public Nullable<decimal> KeyKartGeliri { get; set; }
        public Nullable<short> Sure { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<System.DateTime> OdemeZamani { get; set; }
        public string OdemeYontemi { get; set; }
        public string OdemeYontemiNet { get; set; }
        public string Vardiya { get; set; }
        public string Personel { get; set; }
        public string InvoiceStatus { get; set; }
        public Nullable<int> PerID { get; set; }
        public string Otopark { get; set; }
        public string OdemeKasasi { get; set; }
        public string KartBiletNo { get; set; }
        public string FisNo { get; set; }
        public string FatNo { get; set; }
        public string Ext5 { get; set; }
        public string Ext6 { get; set; }
        public string Ext7 { get; set; }
        public string Ext8 { get; set; }
        public string Saat { get; set; }
        public string VeriTasiyici { get; set; }
        public string Status { get; set; }
        public string Notlar { get; set; }
        public Nullable<int> VardiyaID { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
