//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TavParkBJV
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyKartHareket
    {
        public int Id { get; set; }
        public Nullable<int> Adet { get; set; }
        public string AdSoyadFirmaUnvani { get; set; }
        public string SatisTanimi { get; set; }
        public string Urun { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<decimal> Ucret { get; set; }
        public string OdemeYontemi { get; set; }
        public string Personel { get; set; }
        public Nullable<int> KalanAdet { get; set; }
        public string Ext3 { get; set; }
        public string Ext4 { get; set; }
        public string Otopark { get; set; }
    }
}
