//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TavParkBJV
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeykartUrun
    {
        public int Id { get; set; }
        public Nullable<int> EklenenMiktar { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> UrunId { get; set; }
        public string Personel { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
