//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TavParkBJV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkDBXEntities : DbContext
    {
        public ParkDBXEntities()
            : base("name=ParkDBXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gelirler> Gelirler { get; set; }
        public virtual DbSet<GercekMusteriler> GercekMusteriler { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<TuzelMusteriler> TuzelMusteriler { get; set; }
        public virtual DbSet<CiftGecis> CiftGecis { get; set; }
        public virtual DbSet<ManBarAcma> ManBarAcma { get; set; }
        public virtual DbSet<Vardiya> Vardiya { get; set; }
        public virtual DbSet<tempDbx> tempDbx { get; set; }
        public virtual DbSet<OzetGelir> OzetGelir { get; set; }
        public virtual DbSet<KeyKartHareket> KeyKartHareket { get; set; }
        public virtual DbSet<KeyKartStok> KeyKartStok { get; set; }
        public virtual DbSet<KeykartUrun> KeykartUrun { get; set; }
    }
}
