//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TavParkBJV
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzetGelir
    {
        public int ID { get; set; }
        public Nullable<int> VID { get; set; }
        public Nullable<int> PerID { get; set; }
        public string Otopark { get; set; }
        public Nullable<System.DateTime> VarBasTar { get; set; }
        public Nullable<System.DateTime> VarBtTar { get; set; }
        public string VardiyaSaati { get; set; }
        public string Personel { get; set; }
        public Nullable<decimal> NakitFis { get; set; }
        public Nullable<int> NakitFisAdet { get; set; }
        public Nullable<decimal> NakitFatura { get; set; }
        public Nullable<int> NakitFaturaAdet { get; set; }
        public Nullable<decimal> KrediKartiFis { get; set; }
        public Nullable<int> KrediKartiFisAdet { get; set; }
        public Nullable<decimal> KrediKartiFatura { get; set; }
        public Nullable<int> KrediKartiFaturaAdet { get; set; }
        public Nullable<decimal> CariFatura { get; set; }
        public Nullable<int> CariFaturaAdet { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<decimal> HavaleEftFatura { get; set; }
        public Nullable<int> HavaleEftFaturaAdet { get; set; }
    }
}
