//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TavParkBJV
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuzelMusteriler
    {
        public int MusteriId { get; set; }
        public string Unvan { get; set; }
        public string VergiNo { get; set; }
        public string TelefonNo { get; set; }
        public string PlakaNo { get; set; }
        public string email { get; set; }
        public string AdresText { get; set; }
        public string il { get; set; }
        public string Sehir { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string ilce { get; set; }
        public string Yetkili { get; set; }
        public string VergiDairesi { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
