//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TavParkBJV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vardiya
    {
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string Vardiya1 { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public string DeviceDesing { get; set; }
        public string VStatus { get; set; }
        public Nullable<int> PerID { get; set; }
    }
}
